'use strict';

const genres = [
  'Alternative rock',
  'Ambient music',
  'Baroque music',
  'Bluegrass',
  'Blues',
  'Blues rock',
  'Breakbeat',
  'Classical music',
  'Country music',
  'Dance music',
  'Disco',
  'Drum and bass',
  'Dub',
  'Dubstep',
  'Electro',
  'Electronic dance music',
  'Experimental music',
  'Folk music',
  'Funk',
  'Gospel music',
  'Grunge',
  'Hard rock',
  'Hardcore',
  'Heavy metal',
  'Hip hop music',
  'House music',
  'Indie rock',
  'Industrial music',
  'Instrumental',
  'Jazz',
  'Jazz fusion',
  'Medieval music',
  'Music of Latin America',
  'Musical theatre',
  'New wave',
  'Orchestra',
  'Pop music',
  'Pop rock',
  'Popular music',
  'Progressive music',
  'Progressive rock',
  'Psychedelic music',
  'Punk rock',
  'Reggae',
  'Rhythm and blues',
  'Rock',
  'Salsa',
  'Singing',
  'Ska',
  'Soul music',
  'Techno',
  'Trance music'
];

module.exports = genres;
